### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by rosevinnur** [Bleuh/AvisManga#1]
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  /Users/rosevinnur/Downloads/AvisManga-master/android/app/src/nullnull/debug/google-services.json
  /Users/rosevinnur/Downloads/AvisManga-master/android/app/src/debug/nullnull/google-services.json
  /Users/rosevinnur/Downloads/AvisManga-master/android/app/src/nullnull/google-services.json
  /Users/rosevinnur/Downloads/AvisManga-master/android/app/src/debug/google-services.json
  /Users/rosevinnur/Downloads/AvisManga-master/android/app/src/nullnullDebug/google-services.json
  /Users/rosevinnur/Downloads/AvisManga-master/android/app/google-services.json

**Comment by babariviere** [comment]
Hello,
If you want to use our app (which is clearly not finished) you will have to create your own firebase instance. If you don't know how do to that, just go to the firebase site, there is a lot of doc
